In [4]:
import pandas
import sqlite3
from datetime import datetime

dfs = pandas.read_html('http://rate.bot.com.tw/xrt?Lang=zh-TW')
currency = dfs[0]
currency = currency.ix[:, 0:5]
currency.columns = [u'幣別',u'現金匯率-本行買入',u'現金匯率-本行賣出',u'即期匯率-本行買入',u'即期匯率-本行賣出']
currency[u'幣別'] = currency[u'幣別'].str.extract('\((\w+)\)')
currency['Date'] = datetime.now().strftime('%Y-%m-%d')
currency['Date'] = pandas.to_datetime(currency['Date'])

with sqlite3.connect('C:\\Users\\Administrator\\cuurency.sqlite') as db:
    currency.to_sql('currency', con=db, if_exists='append')

C:\Users\Administrator\Anaconda2\lib\site-packages\ipykernel\__main__.py:9: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

In [6]:
with sqlite3.connect('C:\\Users\\Administrator\\cuurency.sqlite') as db:
    df = pandas.read_sql_query('select * from currency', con = db)

df

    index   幣別 現金匯率-本行買入 現金匯率-本行賣出 即期匯率-本行買入 即期匯率-本行賣出                 Date
0       0  USD     31.08    31.622     31.38     31.48  2017-01-23 00:00:00
1       1  HKD     3.901     4.096     4.021     4.081  2017-01-23 00:00:00
2       2  GBP      38.1     40.03     38.97     39.39  2017-01-23 00:00:00
3       3  AUD     23.46     24.12     23.65     23.88  2017-01-23 00:00:00
4       4  CAD     23.31     24.05     23.58      23.8  2017-01-23 00:00:00
5       5  SGD     21.65     22.43     22.07     22.25  2017-01-23 00:00:00
6       6  CHF     30.79     31.85     31.32     31.61  2017-01-23 00:00:00
7       7  JPY    0.2687    0.2797    0.2751    0.2791  2017-01-23 00:00:00
8       8  ZAR         -         -      2.28      2.36  2017-01-23 00:00:00
9       9  SEK      3.17      3.68      3.51      3.61  2017-01-23 00:00:00
10     10  NZD     22.31     22.94     22.55     22.75  2017-01-23 00:00:00
11     11  THB    0.7871    0.9301    0.8756    0.9156  2017-01-23 00:00:00
12     12  PHP    0.5813    0.7143         -         -  2017-01-23 00:00:00
13     13  IDR   0.00198   0.00268         -         -  2017-01-23 00:00:00
14     14  EUR     33.08     34.23     33.58     33.98  2017-01-23 00:00:00
15     15  KRW    0.0252    0.0291         -         -  2017-01-23 00:00:00
16     16  VND   0.00102   0.00152         -         -  2017-01-23 00:00:00
17     17  MYR     5.994     7.594         -         -  2017-01-23 00:00:00
18     18  CNY     4.508      4.67      4.58      4.63  2017-01-23 00:00:00